geom_abline_p = g_abline = function(p, ...) {return(p + geom_abline(...))}
geom_area_p = g_area = function(p, ...) {return(p + geom_area(...))}
geom_bar_p = g_bar = function(p, ...) {return(p + geom_bar(...))}
geom_bin2d_p = g_bin2d = function(p, ...) {return(p + geom_bin2d(...))}
geom_blank_p = g_blank = function(p, ...) {return(p + geom_blank(...))}
geom_boxplot_p = g_boxplot = function(p, ...) {return(p + geom_boxplot(...))}
geom_col_p = g_col = function(p, ...) {return(p + geom_col(...))}
geom_contour_p = g_contour = function(p, ...) {return(p + geom_contour(...))}
geom_count_p = g_count = function(p, ...) {return(p + geom_count(...))}
geom_crossbar_p = g_crossbar = function(p, ...) {return(p + geom_crossbar(...))}
geom_curve_p = g_curve = function(p, ...) {return(p + geom_curve(...))}
geom_density_p = g_density = function(p, ...) {return(p + geom_density(...))}
geom_density2d_p = g_density2d = function(p, ...) {return(p + geom_density2d(...))}
geom_density_2d_p = g_density_2d = function(p, ...) {return(p + geom_density_2d(...))}
geom_dotplot_p = g_dotplot = function(p, ...) {return(p + geom_dotplot(...))}
geom_errorbar_p = g_errorbar = function(p, ...) {return(p + geom_errorbar(...))}
geom_errorbarh_p = g_errorbarh = function(p, ...) {return(p + geom_errorbarh(...))}
geom_freqpoly_p = g_freqpoly = function(p, ...) {return(p + geom_freqpoly(...))}
geom_hex_p = g_hex = function(p, ...) {return(p + geom_hex(...))}
geom_histogram_p = g_histogram = function(p, ...) {return(p + geom_histogram(...))}
geom_hline_p = g_hline = function(p, ...) {return(p + geom_hline(...))}
geom_jitter_p = g_jitter = function(p, ...) {return(p + geom_jitter(...))}
geom_label_p = g_label = function(p, ...) {return(p + geom_label(...))}
geom_line_p = g_line = function(p, ...) {return(p + geom_line(...))}
geom_linerange_p = g_linerange = function(p, ...) {return(p + geom_linerange(...))}
geom_map_p = g_map = function(p, ...) {return(p + geom_map(...))}
geom_path_p = g_path = function(p, ...) {return(p + geom_path(...))}
geom_point_p = g_point = function(p, ...) {return(p + geom_point(...))}
geom_pointrange_p = g_pointrange = function(p, ...) {return(p + geom_pointrange(...))}
geom_polygon_p = g_polygon = function(p, ...) {return(p + geom_polygon(...))}
geom_qq_p = g_qq = function(p, ...) {return(p + geom_qq(...))}
geom_quantile_p = g_quantile = function(p, ...) {return(p + geom_quantile(...))}
geom_raster_p = g_raster = function(p, ...) {return(p + geom_raster(...))}
geom_rect_p = g_rect = function(p, ...) {return(p + geom_rect(...))}
geom_ribbon_p = g_ribbon = function(p, ...) {return(p + geom_ribbon(...))}
geom_rug_p = g_rug = function(p, ...) {return(p + geom_rug(...))}
geom_segment_p = g_segment = function(p, ...) {return(p + geom_segment(...))}
geom_smooth_p = g_smooth = function(p, ...) {return(p + geom_smooth(...))}
geom_spoke_p = g_spoke = function(p, ...) {return(p + geom_spoke(...))}
geom_step_p = g_step = function(p, ...) {return(p + geom_step(...))}
geom_text_p = g_text = function(p, ...) {return(p + geom_text(...))}
geom_tile_p = g_tile = function(p, ...) {return(p + geom_tile(...))}
geom_violin_p = g_violin = function(p, ...) {return(p + geom_violin(...))}
geom_vline_p = g_vline = function(p, ...) {return(p + geom_vline(...))}
