scale_alpha_p = c_alpha = function(p, ...) {return(p + scale_alpha(...))}
scale_alpha_continuous_p = c_alpha_continuous = function(p, ...) {return(p + scale_alpha_continuous(...))}
scale_alpha_discrete_p = c_alpha_discrete = function(p, ...) {return(p + scale_alpha_discrete(...))}
scale_alpha_identity_p = c_alpha_identity = function(p, ...) {return(p + scale_alpha_identity(...))}
scale_alpha_manual_p = c_alpha_manual = function(p, ...) {return(p + scale_alpha_manual(...))}
scale_color_brewer_p = c_color_brewer = function(p, ...) {return(p + scale_color_brewer(...))}
scale_color_continuous_p = c_color_continuous = function(p, ...) {return(p + scale_color_continuous(...))}
scale_color_discrete_p = c_color_discrete = function(p, ...) {return(p + scale_color_discrete(...))}
scale_color_distiller_p = c_color_distiller = function(p, ...) {return(p + scale_color_distiller(...))}
scale_color_gradient_p = c_color_gradient = function(p, ...) {return(p + scale_color_gradient(...))}
scale_color_gradient2_p = c_color_gradient2 = function(p, ...) {return(p + scale_color_gradient2(...))}
scale_color_gradientn_p = c_color_gradientn = function(p, ...) {return(p + scale_color_gradientn(...))}
scale_color_grey_p = c_color_grey = function(p, ...) {return(p + scale_color_grey(...))}
scale_color_hue_p = c_color_hue = function(p, ...) {return(p + scale_color_hue(...))}
scale_color_identity_p = c_color_identity = function(p, ...) {return(p + scale_color_identity(...))}
scale_color_manual_p = c_color_manual = function(p, ...) {return(p + scale_color_manual(...))}
scale_colour_brewer_p = c_colour_brewer = function(p, ...) {return(p + scale_colour_brewer(...))}
scale_colour_continuous_p = c_colour_continuous = function(p, ...) {return(p + scale_colour_continuous(...))}
scale_colour_date_p = c_colour_date = function(p, ...) {return(p + scale_colour_date(...))}
scale_colour_datetime_p = c_colour_datetime = function(p, ...) {return(p + scale_colour_datetime(...))}
scale_colour_discrete_p = c_colour_discrete = function(p, ...) {return(p + scale_colour_discrete(...))}
scale_colour_distiller_p = c_colour_distiller = function(p, ...) {return(p + scale_colour_distiller(...))}
scale_colour_gradient_p = c_colour_gradient = function(p, ...) {return(p + scale_colour_gradient(...))}
scale_colour_gradient2_p = c_colour_gradient2 = function(p, ...) {return(p + scale_colour_gradient2(...))}
scale_colour_gradientn_p = c_colour_gradientn = function(p, ...) {return(p + scale_colour_gradientn(...))}
scale_colour_grey_p = c_colour_grey = function(p, ...) {return(p + scale_colour_grey(...))}
scale_colour_hue_p = c_colour_hue = function(p, ...) {return(p + scale_colour_hue(...))}
scale_colour_identity_p = c_colour_identity = function(p, ...) {return(p + scale_colour_identity(...))}
scale_colour_manual_p = c_colour_manual = function(p, ...) {return(p + scale_colour_manual(...))}
scale_fill_brewer_p = c_fill_brewer = function(p, ...) {return(p + scale_fill_brewer(...))}
scale_fill_continuous_p = c_fill_continuous = function(p, ...) {return(p + scale_fill_continuous(...))}
scale_fill_date_p = c_fill_date = function(p, ...) {return(p + scale_fill_date(...))}
scale_fill_datetime_p = c_fill_datetime = function(p, ...) {return(p + scale_fill_datetime(...))}
scale_fill_discrete_p = c_fill_discrete = function(p, ...) {return(p + scale_fill_discrete(...))}
scale_fill_distiller_p = c_fill_distiller = function(p, ...) {return(p + scale_fill_distiller(...))}
scale_fill_gradient_p = c_fill_gradient = function(p, ...) {return(p + scale_fill_gradient(...))}
scale_fill_gradient2_p = c_fill_gradient2 = function(p, ...) {return(p + scale_fill_gradient2(...))}
scale_fill_gradientn_p = c_fill_gradientn = function(p, ...) {return(p + scale_fill_gradientn(...))}
scale_fill_grey_p = c_fill_grey = function(p, ...) {return(p + scale_fill_grey(...))}
scale_fill_hue_p = c_fill_hue = function(p, ...) {return(p + scale_fill_hue(...))}
scale_fill_identity_p = c_fill_identity = function(p, ...) {return(p + scale_fill_identity(...))}
scale_fill_manual_p = c_fill_manual = function(p, ...) {return(p + scale_fill_manual(...))}
scale_linetype_p = c_linetype = function(p, ...) {return(p + scale_linetype(...))}
scale_linetype_continuous_p = c_linetype_continuous = function(p, ...) {return(p + scale_linetype_continuous(...))}
scale_linetype_discrete_p = c_linetype_discrete = function(p, ...) {return(p + scale_linetype_discrete(...))}
scale_linetype_identity_p = c_linetype_identity = function(p, ...) {return(p + scale_linetype_identity(...))}
scale_linetype_manual_p = c_linetype_manual = function(p, ...) {return(p + scale_linetype_manual(...))}
scale_radius_p = c_radius = function(p, ...) {return(p + scale_radius(...))}
scale_shape_p = c_shape = function(p, ...) {return(p + scale_shape(...))}
scale_shape_continuous_p = c_shape_continuous = function(p, ...) {return(p + scale_shape_continuous(...))}
scale_shape_discrete_p = c_shape_discrete = function(p, ...) {return(p + scale_shape_discrete(...))}
scale_shape_identity_p = c_shape_identity = function(p, ...) {return(p + scale_shape_identity(...))}
scale_shape_manual_p = c_shape_manual = function(p, ...) {return(p + scale_shape_manual(...))}
scale_size_p = c_size = function(p, ...) {return(p + scale_size(...))}
scale_size_area_p = c_size_area = function(p, ...) {return(p + scale_size_area(...))}
scale_size_continuous_p = c_size_continuous = function(p, ...) {return(p + scale_size_continuous(...))}
scale_size_date_p = c_size_date = function(p, ...) {return(p + scale_size_date(...))}
scale_size_datetime_p = c_size_datetime = function(p, ...) {return(p + scale_size_datetime(...))}
scale_size_discrete_p = c_size_discrete = function(p, ...) {return(p + scale_size_discrete(...))}
scale_size_identity_p = c_size_identity = function(p, ...) {return(p + scale_size_identity(...))}
scale_size_manual_p = c_size_manual = function(p, ...) {return(p + scale_size_manual(...))}
scale_x_continuous_p = c_x_continuous = function(p, ...) {return(p + scale_x_continuous(...))}
scale_x_date_p = c_x_date = function(p, ...) {return(p + scale_x_date(...))}
scale_x_datetime_p = c_x_datetime = function(p, ...) {return(p + scale_x_datetime(...))}
scale_x_discrete_p = c_x_discrete = function(p, ...) {return(p + scale_x_discrete(...))}
scale_x_log10_p = c_x_log10 = function(p, ...) {return(p + scale_x_log10(...))}
scale_x_reverse_p = c_x_reverse = function(p, ...) {return(p + scale_x_reverse(...))}
scale_x_sqrt_p = c_x_sqrt = function(p, ...) {return(p + scale_x_sqrt(...))}
scale_x_time_p = c_x_time = function(p, ...) {return(p + scale_x_time(...))}
scale_y_continuous_p = c_y_continuous = function(p, ...) {return(p + scale_y_continuous(...))}
scale_y_date_p = c_y_date = function(p, ...) {return(p + scale_y_date(...))}
scale_y_datetime_p = c_y_datetime = function(p, ...) {return(p + scale_y_datetime(...))}
scale_y_discrete_p = c_y_discrete = function(p, ...) {return(p + scale_y_discrete(...))}
scale_y_log10_p = c_y_log10 = function(p, ...) {return(p + scale_y_log10(...))}
scale_y_reverse_p = c_y_reverse = function(p, ...) {return(p + scale_y_reverse(...))}
scale_y_sqrt_p = c_y_sqrt = function(p, ...) {return(p + scale_y_sqrt(...))}
scale_y_time_p = c_y_time = function(p, ...) {return(p + scale_y_time(...))}
