stat_bin_p = s_bin = function(p, ...) {return(p + stat_bin(...))}
stat_bin2d_p = s_bin2d = function(p, ...) {return(p + stat_bin2d(...))}
stat_bin_2d_p = s_bin_2d = function(p, ...) {return(p + stat_bin_2d(...))}
stat_bin_hex_p = s_bin_hex = function(p, ...) {return(p + stat_bin_hex(...))}
stat_binhex_p = s_binhex = function(p, ...) {return(p + stat_binhex(...))}
stat_boxplot_p = s_boxplot = function(p, ...) {return(p + stat_boxplot(...))}
stat_contour_p = s_contour = function(p, ...) {return(p + stat_contour(...))}
stat_count_p = s_count = function(p, ...) {return(p + stat_count(...))}
stat_density_p = s_density = function(p, ...) {return(p + stat_density(...))}
stat_density2d_p = s_density2d = function(p, ...) {return(p + stat_density2d(...))}
stat_density_2d_p = s_density_2d = function(p, ...) {return(p + stat_density_2d(...))}
stat_ecdf_p = s_ecdf = function(p, ...) {return(p + stat_ecdf(...))}
stat_ellipse_p = s_ellipse = function(p, ...) {return(p + stat_ellipse(...))}
stat_function_p = s_function = function(p, ...) {return(p + stat_function(...))}
stat_identity_p = s_identity = function(p, ...) {return(p + stat_identity(...))}
stat_qq_p = s_qq = function(p, ...) {return(p + stat_qq(...))}
stat_quantile_p = s_quantile = function(p, ...) {return(p + stat_quantile(...))}
stat_smooth_p = s_smooth = function(p, ...) {return(p + stat_smooth(...))}
stat_spoke_p = s_spoke = function(p, ...) {return(p + stat_spoke(...))}
stat_sum_p = s_sum = function(p, ...) {return(p + stat_sum(...))}
stat_summary_p = s_summary = function(p, ...) {return(p + stat_summary(...))}
stat_summary2d_p = s_summary2d = function(p, ...) {return(p + stat_summary2d(...))}
stat_summary_2d_p = s_summary_2d = function(p, ...) {return(p + stat_summary_2d(...))}
stat_summary_bin_p = s_summary_bin = function(p, ...) {return(p + stat_summary_bin(...))}
stat_summary_hex_p = s_summary_hex = function(p, ...) {return(p + stat_summary_hex(...))}
stat_unique_p = s_unique = function(p, ...) {return(p + stat_unique(...))}
stat_ydensity_p = s_ydensity = function(p, ...) {return(p + stat_ydensity(...))}
